Introduced a `root` attribute to the Spectre configuration.
hiremav/spectre pull request #7
Opened 2024-10-09 14:37 UTC by kladaFOX

# Changelog for Version 1.1.1

**Release Date:** [11th Oct 2024]

**New Features:**

* **Root Attribute in Configuration:**

    * Introduced a `root` attribute to the Spectre configuration. This allows users to specify a custom root directory for loading prompts or other templates.
    * Example usage in initializer:
    ```ruby
    Spectre.setup do |config|
        config.api_key = 'your_openai_api_key'
        config.root = Rails.root # or any custom path
    end
    ```
    * If `root` is not set, Spectre will default to the current working directory (Dir.pwd).
    * This is especially useful when integrating Spectre into other gems or non-Rails projects where the root directory might differ.

* **Prompt Path Detection:**
    * Prompt paths now use the configured `root` to locate the template files. This ensures that Spectre works correctly in various environments where template paths may vary.

2024-10-09 21:33 UTC, matthewblack commented on lib/spectre/prompt.rb
> +          File.join(Spectre.root, 'app', 'spectre', 'prompts')
Is the only going use case for `Spectre.root` to be able to handle a custom prompts path?

If so, should we consider having the config not just the root, but a full relative path to the prompts directly?

2024-10-09 21:33 UTC, matthewblack reviewed
Awesome. One comment / question related to `Spectre.root`

2024-10-10 13:45 UTC, matthewblack commented on lib/spectre/prompt.rb
> +          File.join(Spectre.root, 'app', 'spectre', 'prompts')
Cool!

2024-10-10 13:45 UTC, matthewblack approved these changes
👍

2024-10-10 13:54 UTC, kladaFOX commented
@matthewblack take a look at new prompts feature `Nested Template Support in Prompts`
Now you can pass nested folders for templates as so: 
```ruby
Spectre::Prompt.render(template: 'nested/folder/nested', locals: { query: 'What is AI?' })
```

2024-10-10 15:55 UTC, matthewblack requested changes
Awesome!

For the example, let's update it to be this:

```
app/
  spectre/
    prompts/
      rag/
        system.yml.erb
        user.yml.erb
      classificiation/
        intent/
          system.yml.erb
          user.yml.erb
        entity/
          system.yml.erb
          user.yml.erb
```

2024-10-10 16:01 UTC, merged